name: library-generation
channels:
  - conda-forge
  - defaults
dependencies:
  - deprecated
  - jupyter
  - matplotlib=3.7.*
  - numpy=1.24.*
  - pandas=1.5.*
  - pip
  - pre-commit=3.2.*
  - python=3.9.*
  - rdkit=2021.09.*
  - scikit-image=0.19.*
  - scikit-learn=1.2.*
  - scipy=1.10.*
  - seaborn=0.12.*
  - sqlite=3.41.*
  - xlsxwriter=3.1.*
  - xlrd=2.0.*
  - xlwt=1.3.*
  - pip:
    - git+https://github.com/sevamoo/SOMPY.git@master
