name: library-generation
channels:
  - defaults
  - conda-forge
dependencies:
  - deprecated
  - jupyter
  - matplotlib=3.5.*
  - numpy=1.23.*
  - pandas=1.3.*
  - pip
  - pre-commit=2.20.*
  - python=3.9.*
  - rdkit=2021.09.*
  - scikit-learn=1.0.*
  - scipy=1.7.*
  - seaborn=0.12.*
  - sqlite=3.37.*
  - xlsxwriter=3.0.*
  - xlrd=2.0.*
  - xlwt=1.3.*
