name: library-generation
channels:
  - conda-forge
  - defaults
dependencies:
  - deprecated
  - jupyterlab
  - matplotlib=3.7.*
  - mpl-scatter-density=0.7.*
  - numpy=1.24.*
  - pandas=1.5.*
  - plotly=5.16.*
  - pre-commit=3.2.*
  - pypdf=3.9.*
  - python=3.9.*
  - rdkit=2021.09.*
  - scikit-image=0.19.*
  - scikit-learn=1.3.*
  - scipy=1.10.*
  - seaborn=0.12.*
  - sqlite=3.41.*
  - svgwrite=1.4.*
  - xlsxwriter=3.1.*
  - xlrd=2.0.*
  - xlwt=1.3.*
