# configuration for generatelcmssubmission.py
is_mass: 360.1128  # monoisotopic mass of Fenofibrat
is_formula: C20H21O4Cl  # molecular formula of Fenofibrat
well_plate_size: 384

plate_regex: plate_layout_plate([0-9]+).csv
# plate_regex: test_JG([0-9]+).csv   # this alternative is sometimes useful for non-canonical experiments